# Generated by Django 4.0.3 on 2022-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=30, unique=True)),
                ('rdescription', models.TextField(max_length=100)),
                ('ringredients', models.TextField(max_length=100)),
                ('rstep1', models.TextField(max_length=100)),
                ('rstep2', models.TextField(max_length=100)),
                ('rstep3', models.TextField(max_length=100)),
                ('rstep4', models.TextField(max_length=100)),
                ('rstep5', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_email', models.EmailField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=30)),
            ],
        ),
    ]
