# Generated by Django 4.0.3 on 2023-01-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_recipes_rthumbnail_alter_recipes_ringredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
