# Generated by Django 4.0.3 on 2023-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_remove_recipes_ringredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ringredients',
            field=models.JSONField(default=list),
        ),
    ]
